### ISSUE TITLE
Error whent trying to use this exemple with matrix voice

### ISSUE THREAD

**Issue by Desaydrone** [matrix-io/matrix-core-examples#2] opened 2018-11-05 16:29 UTC
I got this when i try to launch it

`Traceback (most recent call last):
  File "everloop.py", line 15, in <module>
    from utils import register_error_callback
ImportError: cannot import name register_error_callback`

**Comment by Hermitter** [comment] 2018-11-05 17:48
Hi @Desaydrone, can you try removing the utils.py file and redownload it?

```
# Remove Utils.py
rm utils.py utils.pyc

# Download Utils.py
wget "https://raw.githubusercontent.com/matrix-io/matrix-creator-malos/master/src/python_test/utils.py" -O utils.py 
```

**Comment by Desaydrone** [comment] 2018-11-05 20:23
Thanks for your help it works now !!

**Comment by Hermitter** [comment] 2018-11-05 20:27
No problem! Since the issue is resolved, I'll be marking it as closed.

**Closed as completed by Hermitter** 2018-11-05 20:27 UTC
